# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b6b604db7d5035d4e2cfc474e49557986751ade14a4cd13e28f0744b922488c47626795e6bd3a640e6dc3b4e27cc3c500917da1bbce627198ededcbc2c44619

test:
  secret_key_base: e9196103162d1773eecf0b0f469f595139e67c6d3518e3a41cdc44721930200abaca3e0bd3f6ab40b766f379bf37a5a46413339527ba437b3562120b8884354b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
